#!/bin/sh

# After release:perform, do
#
#  ./release-script metrics.goodwill-access-0.1.1 metrics.goodwill-access-0.1.2

last="$1"
new="$2"
git log --no-merges $new ^$last > doc/ChangeLog-$new
git shortlog --no-merges $new ^$last > doc/ShortLog-$new
